### PR TITLE
Track Sources for standard-space outputs

### PR DESCRIPTION
**Pull request by tsalo**
References #3261.

## Changes proposed in this pull request

- Track `Sources` for standard-space outputs

### CODE REVIEW

**Comment by tsalo** [comment]
I think the failures stem from sMRIPrep's new release, but I could be wrong.

**Comment by effigies** [comment]
No. This PR causes files that did not previously have sidecars to get them:

```diff
74a75
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-MNI152NLin2009cAsym_boldref.json
75a77
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-MNI152NLin2009cAsym_desc-brain_mask.json
78a81
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-MNI152NLin6Asym_boldref.json
79a83
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-MNI152NLin6Asym_desc-brain_mask.json
82a87
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-T1w_boldref.json
83a89
> sub-01/func/sub-01_task-mixedgamblestask_run-02_space-T1w_desc-brain_mask.json
```

I will add these to the expected files.

**Comment by effigies** [comment]
@tsalo This is still marked WIP. Did you have more you wanted to do?

**Comment by tsalo** [comment]
Ah, no not in this PR. I'd like to work more on the proximal Sources in future PRs.

**Pull request merged**
