### PR TITLE
ENH: Output TaskName and timing metadata for all resampled BOLD series

### LINKED ISSUE #1549: Convert metadata for sparsely acquired BOLD series
There are four ways to specify a sparse acquisition paradigm, and we need to handle them appropriately:

| Specification | Action needed |
|-|-|
| `RepetitionTime` + `SliceTiming` | Convert `SliceTiming` to `DelayTime` |
| `RepetitionTime` + `DelayTime` | Copy `DelayTime` to derivative BOLD |
| `VolumeTiming` + `SliceTiming` | Copy `VolumeTiming`, convert `SliceTiming` to `AcquisitionDuration` |
| `VolumeTiming` + `AcquisitionDuration` | Copy `VolumeTiming` and `AcquisitionDuration` |

Exactly one of `RepetitionTime` and `VolumeTiming` is required by the spec. If `VolumeTiming` is defined, then `SliceTiming` or `AcquisitionDuration` is required. If `RepetitionTime` does not require `SliceTiming` or `DelayTime`, in which case the acquisition is presumed continuous.

Relation between `SliceTiming`, `AcquisitionDuration` and `DelayTime`:

```Python
sorted_times = sorted(SliceTiming)
# Assuming constant slice-acquisition interval, add interval and final onset
AcquisitionDuration = (SliceTiming[1] - SliceTiming[0]) + SliceTiming[-1]
DelayTime = RepetitionTime - AcquisitionDuration
```

Note that `AcquisitionDuration` is mutually exclusive metadata with `RepetitionTime`, simply to reduce the number of valid ways of specifying sparse acquisition. Annoying, but important to be clear on.

More esoteric volume acquisition protocols, such as non-constant inter-slice intervals, are probably best left to future consideration.

Another thing to consider is whether conversions between these different forms should be packed into pybids, but that I think should be lower priority than just getting this working here.

Follow-up to #1384.

### LINKED ISSUE #2193: Volume timing metadata missing from BOLD series
### What version of fMRIPrep are you using?

20.1.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity

[snip irrelevant bits]

### Summary

RepetitionTime metadata is not associated with CIFTI-2 outputs. VolumeTiming and DelayTime metadata is not carried through from the original data for NIfTI files. There is no metadata for GIFTI files.

### LINKED ISSUE #2294: Multi-part extensions should not infect JSON
fMRIPrep produces outputs named `sub-19_task-MerlinMovie_space-fsLR_den-91k_bold.dtseries.json` to match `sub-19_task-MerlinMovie_space-fsLR_den-91k_bold.dtseries.nii`.

In the [spec](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#preprocessed-coregistered-andor-resampled-volumes), the example given is:

```
pipeline1/
    sub-001/
        func/
            sub-001_task-rest_run-1_space-fsLR_res-1_den-10k_bold.dtseries.nii
            sub-001_task-rest_run-1_space-fsLR_res-1_den-41k_bold.dtseries.nii
            sub-001_task-rest_run-1_space-fsLR_res-2_den-10k_bold.dtseries.nii
            sub-001_task-rest_run-1_space-fsLR_res-2_den-41k_bold.dtseries.nii
            sub-001_task-rest_run-1_space-fsLR_bold.json
```

PyBIDS also looks for sidecars with the extension `.json`, not `.dtseries.json`.

A first pass at this was taken in https://github.com/nipreps/niworkflows/pull/558 but dropped.

There was concern about not having sufficient disambiguation, so if we still can see that, then we need to make an issue on the spec. For my part, I would prefer not to change the spec, but to ensure that we always provide enough entities to ensure that no ambiguity is possible.

### What version of fMRIPrep are you using?

20.2.0

### PR DESCRIPTION
**Pull request by effigies**
## Changes proposed in this pull request

* Add a function to determine output timing parameters from input metadata.
* Pass timing parameters to all BOLD series data sinks to ensure consistent metadata
* Also adds TaskName to relevant data sinks

Closes #1549.
Fixes #2193.
Fixes #2294.

Depends on nipreps/niworkflows#578.

### CODE REVIEW

**Comment by effigies** [comment]
Need to rerun to check expected outputs, but the JSON files can be inspected in artifacts: https://app.circleci.com/pipelines/github/nipreps/fmriprep/51/workflows/a89942cc-7cd9-4b18-acbe-b83c777304b5/jobs/324/artifacts

**Comment by effigies** [comment]
Kind of wild RTD build:

```
Collecting psutil>=5.4
  Downloading psutil-5.7.3.tar.gz (465 kB)
Collecting pyyaml
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting sdcflows~=1.3.2
  Downloading sdcflows-1.3.3-py3-none-any.whl (5.6 MB)
Collecting niworkflows@ git+https://github.com/effigies/niworkflows.git@fix/legacy_dtseries_json
  Cloning https://github.com/effigies/niworkflows.git (to revision fix/legacy_dtseries_json) to /tmp/pip-install-7hlb83i3/niworkflows_7dc7f1f41a2b431c830c641d336b357d
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting sdcflows~=1.3.2
  Downloading sdcflows-1.3.2-py3-none-any.whl (5.6 MB)
Collecting pyyaml
  Downloading PyYAML-5.3.tar.gz (268 kB)
Collecting pyyaml
  Downloading PyYAML-5.2.tar.gz (265 kB)
Collecting pyyaml
  Downloading PyYAML-5.1.2.tar.gz (265 kB)
Collecting pyyaml
  Downloading PyYAML-5.1.1.tar.gz (274 kB)
Collecting pyyaml
  Downloading PyYAML-5.1.tar.gz (274 kB)
Collecting pyyaml
  Downloading PyYAML-3.13.tar.gz (270 kB)
Collecting pyyaml
  Downloading PyYAML-3.12.zip (375 kB)
Collecting pyyaml
  Downloading PyYAML-3.11.zip (371 kB)
Collecting pyyaml
  Downloading PyYAML-3.10.zip (364 kB)
```

**Comment by effigies** [comment]
Niworkflows 1.3.2 is out. This should be ready for review. (Apologies if CircleCI comes back in 2 hours to prove me wrong...)

**Comment by effigies** [comment]
All green. @bpinsard @mgxd @oesteban Are we happy with this for 20.2.1?

**Review by oesteban — APPROVED** [review]
Very much needed. Thanks much, I'm totally in favor of including this within the LTS.

**Comment by bpinsard** [comment]
Great! Looks all good!

**Pull request merged**
