### PR TITLE
FIX: Bug introduced in ``--debug pdb`` PR (#2871)

### PR DESCRIPTION
**Pull request by oesteban**
Only breaks when running with ``--debug pdb`` because `p.exitcode` will not be defined at that point (old line 77).

### CODE REVIEW

**Comment by mgxd** [comment]
I'm not sure what is causing the ds054 crash, but it seems consistent...

**Comment by oesteban** [comment]
> I'm not sure what is causing the ds054 crash, but it seems consistent...

It seems to be reaching https://github.com/nipreps/fmriprep/blob/ec4c21bc37a0e035f22fe958aa216a81ee4ac76c/fmriprep/cli/run.py#L148 without issues, and then we don't seem to handle very well the problem, which must happen in relation to the citation boilerplate.

**Comment by oesteban** [comment]
I might have broken the report generation?

https://github.com/nipreps/fmriprep/blob/ec4c21bc37a0e035f22fe958aa216a81ee4ac76c/fmriprep/cli/run.py#L189

**Review by effigies — APPROVED** [review]
ds054 passing

**Comment by oesteban** [comment]
Good catch with the sentry problem :)

**Pull request merged**
