### PR TITLE
MAINT: Upgrade Docker to FSL 6

### PR DESCRIPTION
**Pull request by mgxd**
Local test passed, so let's see how this goes.

### CODE REVIEW

**Comment by mgxd** [comment]
For reference, here are a few reports of a subject using `flirt -bbr`

current master (5929041): https://3428-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html
fsl6: https://3427-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html

I don't think this is as controversial as initially believed.

**Comment by oesteban** [comment]
The problem is FSL bet - it easily gets stuck with long paths if I recall correctly. I thought there was an open issue on nipype, but I can't seem to find it. Was the problem perhaps addressed?

**Comment by mgxd** [comment]
does d3a4d33 address the name concerns, or were you referring to something different?

**Comment by effigies** [comment]
@oesteban Just a bump on this. Should be a very quick yes/no.

**Comment by effigies** [comment]
@mgxd Can you open PRs (they won't need to be merged) in niworkflows, sdcflows and smriprep? Let's give their CIs a chance to find errors, too.

**Comment by effigies** [comment]
Okay, I think we've tested with all dependencies...

**Pull request merged**
