### PR TITLE
BF(DOC): use a BIDS compliant _mask instead of old BEP03 _roi to point to lesion mask

### PR DESCRIPTION
**Pull request by yarikoptic**
Not sure if the specific name is the best one, since does not point
explicitly to T1w as the orig of that mask, and either label should
may be made extended instead of abbreviated L.

But in either case, old doc example is clearly wrong thus this fix

Attn @michael-sun

### CODE REVIEW

**Comment by effigies** [comment]
Before we can update the docs, we need to accept the standard ROI masks.

**Comment by yarikoptic** [comment]
oh, right... I have tried to spot which code is relying on those `_roi` files but failed to find any.

**Comment by effigies** [comment]
It's in smriprep. Apologies for the web of dependencies; the idea is to make identical anatomical preprocessing available to dmriprep or aslprep or whatevercomesnextprep.

**Comment by effigies** [comment]
Docs are being updated to match behavior in #2943. They will be updated again when behavior conforms to BIDS Derivatives spec, targeting 23.1.0.

**Pull request closed without merging**
