### PR TITLE
RF: Split fMRIPrep into fit and derivatives workflows

### PR DESCRIPTION
**Pull request by effigies**
This begins on #2207.

Todo:

* [x] Validate correct operation of sMRIPrep integration with shim workflow
* [x] Use smriprep fit and derivatives workflows separately, working toward `--minimal` derivatives mode
* [x] Sink sdcflows' preprocessed fieldmap and fetch from derivatives directory
* [x] Refactor BOLD stages to use the `input -> proc -> derivatives -> buffer` pattern
* [x] Reduce fit stages to generate minimal files
* [ ] Thorough documentation of `--minimal`

## Documentation that should be reviewed
There will be some.

### CODE REVIEW

**Comment by effigies** [comment]
Current state:

```
sub-04/
├── anat
│   ├── sub-04_desc-brain_mask.json
│   ├── sub-04_desc-brain_mask.nii.gz
│   ├── sub-04_desc-preproc_T1w.json
│   ├── sub-04_desc-preproc_T1w.nii.gz
│   ├── sub-04_desc-preproc_T2w.json
│   ├── sub-04_desc-preproc_T2w.nii.gz
│   ├── sub-04_dseg.nii.gz
│   ├── sub-04_from-fsnative_to-T1w_mode-image_xfm.txt
│   ├── sub-04_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│   ├── sub-04_from-T1w_to-fsnative_mode-image_xfm.txt
│   ├── sub-04_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│   ├── sub-04_label-CSF_probseg.nii.gz
│   ├── sub-04_label-GM_probseg.nii.gz
│   ├── sub-04_label-WM_probseg.nii.gz
│   ├── sub-04_run-01_from-orig_to-T1w_mode-image_xfm.txt
│   └── sub-04_run-02_from-orig_to-T1w_mode-image_xfm.txt
├── figures
│   ├── sub-04_desc-conform_T1w.html
│   ├── sub-04_desc-reconall_T1w.svg
│   ├── sub-04_dseg.svg
│   └── sub-04_space-MNI152NLin2009cAsym_T1w.svg
├── func
│   ├── sub-04_task-floc_run-01_desc-coreg_boldref.json
│   ├── sub-04_task-floc_run-01_desc-coreg_boldref.nii.gz
│   ├── sub-04_task-floc_run-01_desc-hmc_boldref.json
│   ├── sub-04_task-floc_run-01_desc-hmc_boldref.nii.gz
│   ├── sub-04_task-floc_run-01_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│   ├── sub-04_task-floc_run-01_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│   ├── sub-04_task-floc_run-01_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│   ├── sub-04_task-floc_run-01_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
```

Adding fieldmap processing back this morning.

**Comment by effigies** [comment]
@mgxd @oesteban @feilong Here's the current fit-only output. Anything obvious missing? Should we get started on a resampler from BOLD to MNI using just derivatives?

```
sub-04
├── anat
│   ├── sub-04_desc-brain_mask.json
│   ├── sub-04_desc-brain_mask.nii.gz
│   ├── sub-04_desc-preproc_T1w.json
│   ├── sub-04_desc-preproc_T1w.nii.gz
│   ├── sub-04_desc-preproc_T2w.json
│   ├── sub-04_desc-preproc_T2w.nii.gz
│   ├── sub-04_dseg.nii.gz
│   ├── sub-04_from-fsnative_to-T1w_mode-image_xfm.txt
│   ├── sub-04_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│   ├── sub-04_from-T1w_to-fsnative_mode-image_xfm.txt
│   ├── sub-04_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│   ├── sub-04_label-CSF_probseg.nii.gz
│   ├── sub-04_label-GM_probseg.nii.gz
│   ├── sub-04_label-WM_probseg.nii.gz
│   ├── sub-04_run-01_from-orig_to-T1w_mode-image_xfm.txt
│   ├── sub-04_run-02_from-orig_to-T1w_mode-image_xfm.txt
│   ├── sub-04_run-03_from-orig_to-T1w_mode-image_xfm.txt
│   ├── sub-04_run-04_from-orig_to-T1w_mode-image_xfm.txt
│   ├── sub-04_run-05_from-orig_to-T1w_mode-image_xfm.txt
│   └── sub-04_run-06_from-orig_to-T1w_mode-image_xfm.txt
├── figures
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-phasediff_fieldmap.svg
│   ├── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-phasediff_fieldmap.svg
│   ├── sub-04_desc-conform_T1w.html
│   ├── sub-04_desc-reconall_T1w.svg
│   ├── sub-04_dseg.svg
│   └── sub-04_space-MNI152NLin2009cAsym_T1w.svg
├── fmap
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-coeff0_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-coeff1_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-magnitude_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-preproc_fieldmap.json
│   ├── sub-04_acq-fMRI_run-01_fmapid-auto00000_desc-preproc_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-coeff0_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-coeff1_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-magnitude_fieldmap.nii.gz
│   ├── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-preproc_fieldmap.json
│   └── sub-04_acq-fMRI_run-02_fmapid-auto00001_desc-preproc_fieldmap.nii.gz
├── func
│   ├── sub-04_task-floc_run-01_desc-coreg_boldref.json
│   ├── sub-04_task-floc_run-01_desc-coreg_boldref.nii.gz
│   ├── sub-04_task-floc_run-01_desc-hmc_boldref.json
│   ├── sub-04_task-floc_run-01_desc-hmc_boldref.nii.gz
│   ├── sub-04_task-floc_run-01_from-boldref_to-auto00000_mode-image_xfm.json
│   ├── sub-04_task-floc_run-01_from-boldref_to-auto00000_mode-image_xfm.txt
│   ├── sub-04_task-floc_run-01_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│   ├── sub-04_task-floc_run-01_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│   ├── sub-04_task-floc_run-01_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│   ├── sub-04_task-floc_run-01_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
│   ├── sub-04_task-floc_run-02_desc-coreg_boldref.json
│   ├── sub-04_task-floc_run-02_desc-coreg_boldref.nii.gz
│   ├── sub-04_task-floc_run-02_desc-hmc_boldref.json
│   ├── sub-04_task-floc_run-02_desc-hmc_boldref.nii.gz
│   ├── sub-04_task-floc_run-02_from-boldref_to-auto00000_mode-image_xfm.json
│   ├── sub-04_task-floc_run-02_from-boldref_to-auto00000_mode-image_xfm.txt
│   ├── sub-04_task-floc_run-02_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│   ├── sub-04_task-floc_run-02_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│   ├── sub-04_task-floc_run-02_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│   ├── sub-04_task-floc_run-02_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
│   ├── sub-04_task-floc_run-03_desc-coreg_boldref.json
│   ├── sub-04_task-floc_run-03_desc-coreg_boldref.nii.gz
│   ├── sub-04_task-floc_run-03_desc-hmc_boldref.json
│   ├── sub-04_task-floc_run-03_desc-hmc_boldref.nii.gz
│   ├── sub-04_task-floc_run-03_from-boldref_to-auto00001_mode-image_xfm.json
│   ├── sub-04_task-floc_run-03_from-boldref_to-auto00001_mode-image_xfm.txt
│   ├── sub-04_task-floc_run-03_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│   ├── sub-04_task-floc_run-03_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│   ├── sub-04_task-floc_run-03_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│   ├── sub-04_task-floc_run-03_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
│   ├── sub-04_task-floc_run-04_desc-coreg_boldref.json
│   ├── sub-04_task-floc_run-04_desc-coreg_boldref.nii.gz
│   ├── sub-04_task-floc_run-04_desc-hmc_boldref.json
│   ├── sub-04_task-floc_run-04_desc-hmc_boldref.nii.gz
│   ├── sub-04_task-floc_run-04_from-boldref_to-auto00001_mode-image_xfm.json
│   ├── sub-04_task-floc_run-04_from-boldref_to-auto00001_mode-image_xfm.txt
│   ├── sub-04_task-floc_run-04_from-boldref_to-T1w_mode-image_desc-coreg_xfm.json
│   ├── sub-04_task-floc_run-04_from-boldref_to-T1w_mode-image_desc-coreg_xfm.txt
│   ├── sub-04_task-floc_run-04_from-orig_to-boldref_mode-image_desc-hmc_xfm.json
│   └── sub-04_task-floc_run-04_from-orig_to-boldref_mode-image_desc-hmc_xfm.txt
└── log
    └── 20230817-090005_ced9e695-8166-402c-9f3c-7a7baa6620af
        └── fmriprep.toml

6 directories, 77 files
```

If I can find time between calls today, I'll update the workflow to work with the recently merged sdcflows changes.

Also, how do people feel about merging this into `next` and setting up `next` to push a `:next-{date}` tag to DockerHub? I'm not ready to spend a bunch of time getting CI unbroken, but would like to start testing this on OpenNeuro data to compare speed and filesystem usage changes over 23.1.x.

**Comment by mgxd** [comment]
Is the HTML report still produced? Should the goodvoxels mask be produced too? Otherwise, looks reasonable to me.

Also, I'm good with pushing to `next`

**Comment by feilong** [comment]
Perhaps also include the surface `.gii` files under `anat`? I think we'll need the surface geometry files at some point for resampling onto cortical surface.
Besides this, the generated files look good to me.

**Pull request merged**
