### PR TITLE
ENH: Flexibilize "sophisticated" pepolar to allow monomodal execution

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by effigies** [comment]
What use case is this intended to support?

**Comment by oesteban** [comment]
I have a dataset with all four AP/PA/LR/RL EPIs. This should be easy to handle by topup.

**Comment by effigies** [comment]
What about len(suffixes) >= 2, then? Or we could drop the length check altogether and rely on sdcflows to not create estimators with too few inputs.

**Comment by oesteban** [comment]
> What about len(suffixes) >= 2, then? Or we could drop the length check altogether and rely on sdcflows to not create estimators with too few inputs.

The idea is that the four images are of the same modality. That would allow for epi + bold (which should be capture by the other condition, and disallow more than 2 images)

**Comment by effigies** [comment]
Got it. Let's add a comment, as I'm sure I'll forget.

**Comment by oesteban** [comment]
Sure, I'll add it later today

**Review by effigies — APPROVED** [review]

**Pull request merged**
