### PR TITLE
REL: 20.2.1

### PR DESCRIPTION
**Pull request by effigies**
Are we good to go?

### CODE REVIEW

**Comment by effigies** [comment]
@bpinsard If you'd like to do the honors, I think it would be good for you to officially release as the LTS manager. We have our [release checklist](https://github.com/nipreps/fmriprep/wiki/Release-checklist) that could probably use some revision, but here's what I would do. After merge:

```
git fetch upstream
git checkout maint/20.2.x
git merge --ff-only upstream/maint/20.2.x
git tag -a 20.2.1
git push upstream 20.2.1
```

For the tag message, I just use the changelog with the `=====` replaced with an empty line. In this case it would be:

```
20.2.1 (November 06, 2020)

Bug-fix release in the 20.2.x LTS series.

This release adds missing metadata to GIFTI and CIFTI-2 derivatives and fixes a logging
bug affecting a small number of datasets.

Additionally the ``--output-layout bids`` flag will now output fMRIPrep derivatives directly
into the output directory, nesting FreeSurfer derivatives by default in
``<output>/sourcedata/freesurfer``. This layout allows the output root to be a valid BIDS
Derivatives dataset, simplifying data management and provenance tracking with content tracking
tools, such as `DataLad <https://handbook.datalad.org/>`__. This layout will likely become the
default in future release series.

  * ENH: Output TaskName and timing metadata for all resampled BOLD series (#2320)
  * ENH: Add --output-layout CLI option to enable BIDS (YODA) mode (#2303)
  * ENH: Add Docker authentication to increase pull rate limit (#2316)
  * FIX: Specify logger for warning (#2298)
```

**Comment by bpinsard** [comment]
Thanks for the detailed pipeline and checklist. I will do it this afternoon asap.

**Comment by bpinsard** [comment]
@effigies It looks like I do not have the write access to the nipreps/fmriprep repo to push the tag.

**Comment by effigies** [comment]
Ah. I'll give you permissions. Also, please merge this PR before tagging, since it includes the changelog.

**Comment by effigies** [comment]
I made you a maintainer. Let me know if that works for you. I can bump to admin, but I think the only new thing that allows is deleting the repo, so I assume you don't need that.

**Comment by bpinsard** [comment]
Thanks, that worked. For the pypi and docker I am not sure if this is triggered automatically, otherwise I think that I do not have the permissions to push the new version.

**Comment by effigies** [comment]
Those will get pushed by Circle once all the tests are done.

**Pull request merged**
