### PR TITLE
FIX: ensure `fieldwarp` == `identity` during resampling of processed multi-echo data

### PR DESCRIPTION
**Pull request by markushs**
## Changes proposed in this pull request

Likely fixes issues reported in https://github.com/nipreps/fmriprep/issues/2727
## Documentation that should be reviewed
No

### CODE REVIEW

**Comment by effigies** [comment]
@oesteban Could I get a second pair of eyes on this? I think it's right, but I want to be extra careful.

@markushs Are you able to test this patch on your installation? Do you need any guidance?

**Comment by markushs** [comment]
> @markushs Are you able to test this patch on your installation? Do you need any guidance?

@effigies I'll try to bind an edited version of `base.py` into my singularity image. Should work, but as this image reflects "vanilla" 21.0.1 I won't be able to test the patch against newly merged stuff.

**Comment by markushs** [comment]
My tests appear successful.
`*_space-T1w*_bold.nii.gz`-files are now identical to volumes in native functional "scanner"-space transformed to space-T1w using the fmriprep-generated `*_from-scanner_to-T1w_mode-image_xfm.txt`.

`command.txt` in `bold_t1_trans_wf/bold_to_t1w_transform` looks correct for all volumes, with 2x `--transform identity` (i added the backslashes for readibility): 
image

Not sure what the empty `_dpop` function in the now deleted lines was doing, but everything looks good without, so maybe consider also getting rid of the function definition?

**Comment by effigies** [comment]
Thanks for confirming!

**Review by oesteban — APPROVED** [review]
LGTM (opened #2732 as a reminder for myself)

**Pull request merged**
