### PR TITLE
MAINT: Keep pip and setuptools with support for Python 3.5

### PR DESCRIPTION
**Pull request by oesteban**
Follows #2446.

### CODE REVIEW

**Review by mgxd — APPROVED** [review]
LGTM

**Comment by mgxd** [comment]
What's the expected lifecycle of older, non-LTS minor releases?

**Comment by oesteban** [comment]
Good question. But in the case of the spatial normalization bug it is
something we want to fix even if support of 20.1.x were ended.

**Comment by effigies** [comment]
Wouldn't it just make sense to recommend upgrading to 20.2, since this affects all 20.1?

**Comment by oesteban** [comment]
> Wouldn't it just make sense to recommend upgrading to 20.2, since this affects all 20.1?

Yes, I think we are already doing that anyways. Some people may have started some long study with 20.1 and will want to stick with it - although the best advice would be upgrading indeed.

I'd be happy to call 20.1.x and end support after this bug is fixed. Only if something as big as this one surfaces, we might want to provide a fixed release. If the patch wouldn't be as easy, then we may want to ban 20.1.x completely - but let's give this series a chance, right?

**Comment by oesteban** [comment]
> What's the expected lifecycle of older, non-LTS minor releases?

Should we open a pinned issue, start conversations and maybe raise this question in a roundup with some thought-through proposal?

**Pull request merged**
