### PR TITLE
MNT: Update BIDS validator to 1.8.0

### PR DESCRIPTION
**Pull request by effigies**
Follow-up to #2409, to test whether the HED refactor solved our issues.

### CODE REVIEW

**Comment by effigies** [comment]
Failure: https://github.com/bids-standard/bids-validator/issues/1307

**Comment by oesteban** [comment]
Can we update to =~1.6.0 for now?

**Comment by mgxd** [comment]
> Can we update to =~1.6.0 for now?

I believe `1.5.7` was the last version that did not require network access

**Comment by effigies** [comment]
Yeah, the current pin is the last working version. I was seeing if our issue was resolved. It may have been, but we bundled a significant change in a patch release.

**Comment by effigies** [comment]
Passed the validation stage. This should be good to go on green.

**Pull request merged**
