### PR TITLE
STY: Apply pyupgrade suggestions

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
## Changes proposed in this pull request

`pyupgrade --py310-plus`

Also manually change a few `.format()` calls to f-strings.

### CODE REVIEW

**Comment by effigies** [comment]
I want to hold off on this until the full release, then we'll probably just do what we're doing over in smriprep. We can take care of pyupgrade, flake8, and all that in a single PR.

**Comment by effigies** [comment]
I think this should be covered by ruff now.

**Comment by DimitriPapadopoulos** [comment]
Not entirely. For example, switching to f-strings is not covered by ruff (pyupgrade rules).

**Comment by effigies** [comment]
Ah, do you want to go ahead and re-upgrade? Note that `wrapper/` needs to be excluded, since we're still maintaining Python 2.7 compatibility for that package.

**Comment by DimitriPapadopoulos** [comment]
Let me have a look first:
- exclude wrapper
- perhaps add other ruff rules that may be associated to the pyupgrade suggestions

**Pull request closed without merging**
