### PR TITLE
MNT: Pin environment

### PR DESCRIPTION
**Pull request by effigies**
Trying to apply #2853's environment pin approach.

Here, I took the `conda=` line from `21.0.3`'s environment, and added lines from nipreps-containers [here](https://github.com/nipreps-containers/miniconda/blob/c68c59bae48662a5110d7b6a7b66eb8d00a7ffee/Dockerfile#L76-L129). I then removed pretty much everything non-numeric that can be installed through pip, ending with:

```YAML
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=4.11.0=py38h578d9bd_0
  - python=3.8
  - mkl=2021.3
  - mkl-service=2.4
  - nodejs=16
  - numpy=1.20
  - pandas
  - scikit-image=0.19
  - scikit-learn=0.24
  - scipy=1.6
  - seaborn=0.11
  - traits=6.2
prefix: /opt/conda
```

Then I created a new environment, installed fmriprep and re-exported:

```console
$ conda env create -n tmp-fmriprep-21-0 -f docker/files/environment.yml
$ conda activate tmp-fmriprep-21-0
$ pip install .
$ conda env export
```

Then I dropped nipreps tools, since they're very likely to get re-updated between releases and they're all pure Python.

### CODE REVIEW

**Comment by mgxd** [comment]
will need to update circle's docker orb

**Comment by effigies** [comment]
It needs fixing on 20.2.x as well. Would you mind fixing it there, and I can merge forward into this PR?

**Comment by mgxd** [comment]
https://github.com/nipreps/fmriprep/commit/4feb341048a01d74eb6c6ce77496f19f42d2a9bf

**Comment by effigies** [comment]
21.0.x will not have further releases. Closing.

**Pull request closed without merging**
