### PR TITLE
PIN: NiPreps dependencies to development branches

### PR DESCRIPTION
**Pull request by mgxd**
Spawned after discussion with @oesteban in https://github.com/nipreps/fmriprep/pull/2372#issuecomment-790015350

### CODE REVIEW

**Comment by mgxd** [comment]
@oesteban was niworkflows 1.4.0rc5 released from a yet-to-be pushed branch?
https://github.com/nipreps/niworkflows/commit/2428186ac8cb927b96f69d73fb59d3c72e96c6a9

**Comment by oesteban** [comment]
Oh yes, I need to merge `rel/1.4.0rc5` into master - sorry about that.

**Comment by mgxd** [comment]
right...forgot about the dreaded sdcflows 2.0 migration...

**Comment by oesteban** [comment]
Should we just close this one and use link dependencies only during testing PRs?

**Comment by mgxd** [comment]
I still think there's some merit to pinning the closely related nipreps packages to master.

**Review by oesteban — APPROVED** [review]
Okay, let's try this and see how it goes. I think the most important change is that of the `test_deploy_pypi` on circle, and it seems like a good idea at this moment.

**Comment by oesteban** [comment]
I don't think we can use dependency links for niworkflows and sdcflows before #2392 is merged. Why don't we just merge the changes to CircleCI's config here and update the dependencies there?

**Comment by mgxd** [comment]
Totally agree - opened #2472 in favor of this

**Pull request closed without merging**
