### PR TITLE
FIX: maint/20.2.x builds

### PR DESCRIPTION
**Pull request by effigies**
This is going to be debuggy.

### CODE REVIEW

**Comment by effigies** [comment]
@mgxd @bpinsard Any objections to these updates? Should we run a numeric stability check before merging?

**Comment by mgxd** [comment]
we are updating a lot of python packages - let's wait for some results/opinions from @bpinsard @ltetrel before proceeding

**Comment by ltetrel** [comment]
Hi @mgxd, basile is in paternity leave until January I think. As for myself I have no background on the release of the LTS itself, so better ask him. For the reproducibility, we are discussing it also in the https://mattermost.brainhack.org/brainhack/channels/fmriprep_reproducibility
@yohanchatelain is about to run the experiments, I would be happy to help on that next week,

**Comment by effigies** [comment]
I am currently running a bitwise determinism check between 20.2.6 and this branch on a pared down version of ds005. We'll see what that looks like...

```
fmriprep-docker /data/bids/minineuro/ds000005 /data/out/ds000005-fmriprep_lts1 participant \
    --ignore slicetiming -vv --skip-bids-validation --participant-label 01 \
    -w /data/scratch/ds000005-fmriprep_lts1 --fs-subjects-dir /data/out/ds000005-fmriprep/freesurfer \
    -i nipreps/fmriprep:20.2.6 --omp-nthreads 1 --random-seed 1234
```

```
fmriprep-docker /data/bids/minineuro/ds000005 /data/out/ds000005-fmriprep_lts2 participant \
    --ignore slicetiming -vv --skip-bids-validation --participant-label 01 \
    -w /data/scratch/ds000005-fmriprep_lts2 --fs-subjects-dir /data/out/ds000005-fmriprep/freesurfer \
    -i nipreps/fmriprep:fixlts --omp-nthreads 1 --random-seed 1234
```

**Comment by ltetrel** [comment]
If you want a (fast) checksum comparison between your two iterations, don't hesitate to use:
https://github.com/SIMEXP/fmriprep-reproducibility/blob/master/fmriprep-reproducibility/tests/test_checksum.py

Actually if you pull the repo, copy paste your outputs to `./outputs/ieee` and rename appropriately `fmriprep_ds000XXX_X` it should work after running `pytest`.

**Comment by effigies** [comment]
Did not achieve bit-for-bit determinism. Pushed a hacky 662fd8723c8c770818c9f4b290660bf79a4e5e67 to fix the specific issue, and can work toward a more forward-compatible base in January.

**Pull request closed without merging**
