### PR TITLE
FIX: Raise informative error when duplicate subworkflows are added

### PR DESCRIPTION
**Pull request by effigies**
Inspired by https://github.com/nipreps/nibabies/issues/82.

`workflow.connect()` is tab-shifted but otherwise unchanged.

### CODE REVIEW

**Review by mgxd — COMMENTED** [review]
Should we generalize this to the whole workflow building process? i.e.
https://github.com/nipreps/fmriprep/blob/237523c0926fd84b60d6249088c13167455e5a16/fmriprep/cli/workflow.py#L82

I know we are building within a subprocess, which might make this error reporting too complicated, but it would be nice to handle this in the case of every `connect` statement

**Comment by effigies** [comment]
The nice thing about where I put it is that we have the specific file name as well as the exception, so we can be pretty precise. Wrapping the line you suggest would lose that.

Besides, what are the other cases where there might be a collision? The subject ID is in the subject workflow name, and all the entities are in the functional workflow name, so AFAIK the `.nii`/`.nii.gz` duplication is the only possibility. If we see others, it would be good to get them, but a quick survey of old issues showed one pybids bug, and a bunch of this.

**Comment by mgxd** [comment]
Sounds good - I agree it does give a better message there. If the duplication error ever comes up again we can revisit this - but I'm fine with the changes as is

**Comment by effigies** [comment]
Cool. Guess I'll wait on the nibabies issue, to see if there is some other way that we're hitting this.

**Comment by mgxd** [comment]
The nibabies error was due to an internal bug, merging.

**Pull request merged**
