### PR TITLE
MAINT: Normalize code style of ``workflows.confounds``

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by effigies** [comment]
If this is just black, merge at will.

**Comment by effigies** [comment]
Or even just push the commit directly to master.

**Comment by oesteban** [comment]
> If this is just black, merge at will.

It's just black, but for some reason, it didn't normalize the single-quotes to double-quotes. So I did it manually and want to check I did not screw up :)

**Comment by oesteban** [comment]
> We disabled the quote normalization in config a while back.

I've looked through `setup.cfg` in an attempt to find that but now I see it is in the pyproject.toml file.

Is there a particular reason for this? We have used both styles indistinctly, I would understand if we were following some convention...

**Comment by effigies** [comment]
The reason is mostly that black gets applied sometimes and it became hard to review PRs that mixed semantic changes and style fixes in unrelated portions of the code.

**Comment by effigies** [comment]
Yup, that's fine and what I'd prefer. Or even just separating the style commits.

**Comment by oesteban** [comment]
Seems like ds210 fails for some other reason - https://app.circleci.com/pipelines/github/nipreps/fmriprep/678/workflows/1802c485-cf84-4fbe-9161-9734fa71a532/jobs/3731

**Pull request merged**
