### PR TITLE
MNT: Install ANTs from conda-forge

### LINKED ISSUE #2915: Transition more packages to conda
### What would you like to see added in fMRIPrep?

* FSL is providing conda packages at a self-hosted channel: https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/
* Convert3D has a [conda-forge feedstock](https://github.com/conda-forge/convert3d-feedstock)

Using conda will hopefully make it cheaper to upgrade our Docker images. FSL in particular separating its tools out into many packages should also make the images lighter, and we will have fewer packages to reinstall when we do need to rerun the line.

### Do you have any interest in helping implement the feature?

Yes

### Additional information / screenshots

An effort to package ANTs stalled: https://github.com/ANTsX/ANTs/issues/1199

John's AFNI build hasn't been updated since 2020, so shouldn't use it for Docker. I would be okay using it for tests outside Docker (e.g., on GitHub actions).

FreeSurfer and Connectome Workbench have had third-party builds, but they do not seem to be actively maintained.

### PR DESCRIPTION
**Pull request by effigies**
Closes #2915. Again.

### CODE REVIEW

**Comment by effigies** [comment]
AFNI build step failing weirdly:

```
 > [afni 2/2] RUN mkdir -p /opt/afni-latest     && curl -fsSL --retry 5 https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz     | tar -xz -C /opt/afni-latest --strip-components 1     --exclude "linux_openmp_64/*.gz"     --exclude "linux_openmp_64/funstuff"     --exclude "linux_openmp_64/shiny"     --exclude "linux_openmp_64/afnipy"     --exclude "linux_openmp_64/lib/RetroTS"     --exclude "linux_openmp_64/lib_RetroTS"     --exclude "linux_openmp_64/meica.libs"     && find /opt/afni-latest -type f -not (         -name "3dTshift" -or         -name "3dUnifize" -or         -name "3dAutomask" -or         -name "3dvolreg" ) -delete:
#0 0.277 curl: (60) SSL: no alternative certificate subject name matches target host name 'afni.nimh.nih.gov'
#0 0.278 More details here: https://curl.se/docs/sslcerts.html
#0 0.278 
#0 0.278 curl failed to verify the legitimacy of the server and therefore could not
#0 0.278 establish a secure connection to it. To learn more about this situation and
#0 0.278 how to fix it, please visit the web page mentioned above.
#0 0.280 
#0 0.280 gzip: stdin: unexpected end of file
#0 0.281 tar: Child returned status 1
#0 0.281 tar: Error is not recoverable: exiting now
```

**Comment by effigies** [comment]
Failing because of https://github.com/nipreps/niworkflows/pull/818.

**Comment by effigies** [comment]
```
REPOSITORY                TAG               IMAGE ID       CREATED         SIZE
nipreps/fmriprep          latest            7e9957f60b4f   3 minutes ago   6.82GB
```

**Comment by effigies** [comment]
cc @yarikoptic

**Comment by mgxd** [comment]
Looks like a wonky cache, perhaps needs a bump?

**Comment by effigies** [comment]
New size: 6.82GB

**Pull request merged**
