### PR TITLE
Add a --fs-reuse-base option to reuse existing freesurfer outputs from a longitudinal pipeline

### PR DESCRIPTION
**Pull request by bpinsard**
## Changes proposed in this pull request

Integrate options/configs for https://github.com/nipreps/smriprep/pull/371

### CODE REVIEW

**Comment by effigies** [comment]
I hate to do this to you, but we're going to be merging in the `next` branches to smriprep and fmriprep pretty soon. I'm afraid you have some rebasing in front of you.

**Comment by bpinsard** [comment]
Lol thanks for the heads-up, no problem. I will start to update myself on the `next` changes. Is there an overview/working document that I could start reading from? Thanks!

**Comment by effigies** [comment]
We don't exactly have a single roadmap we're updating. Issues have been opened, closed and duplicated. I've tried to track them with the [next label](https://github.com/nipreps/fmriprep/pulls?q=is%3Apr+is%3Aclosed+sort%3Acreated-desc+label%3Anext). (And [on smriprep](https://github.com/nipreps/smriprep/issues?q=label%3Anext+).)

The basic idea is that we're refactoring into a minimal "fit" workflow and an optional apply workflow. The goal is to spend archive space on the things that are expensive to compute and leave the deterministic derivatives to the end user if they want them. (We're working on wiring those up by default now.)

Probably the best place for you to start is here:

https://github.com/nipreps/smriprep/blob/next/smriprep/workflows/anatomical.py#L949-L1001

That's the bit for FreeSurfer, and gives a sense of the overall architecture: Check for pre-computed derivatives, build out workflow if they aren't found, and save them to the output directory. `buffer` nodes are used as checkpoints that we either populate from precomputed derivatives or subworkflows.

**Comment by bpinsard** [comment]
Tests should pass when https://github.com/nipreps/smriprep/pull/371 will be merged into smriprep `next`.

**Pull request closed without merging**
